import { CollectionArtwork } from "./collectionArtwork.model";

export class ExtraArtworks {
    artworks: CollectionArtwork[] = [

        new CollectionArtwork('Pray for More" campaign, Stuttgart, Germany', "Les Levine", "1988", "https://likeyou.com/wp-content/uploads/2018/03/Les_Levine_Pray_for_More_Portrait_with_Les_Levine_1989-90_mai36_18_likeyou.jpg", 'Pray for More" campaign, Stuttgart, Germany, Les Levine, 1988'),
        new CollectionArtwork("Grosse Fatigue", "Camille Henrot", "2013", "https://www.moma.org/media/W1siZiIsIjI5NDk3OCJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MTQ0MFx1MDAzZSJdXQ.jpg?sha=cc97ad8174c4730a", "Grosse Fatigue, Camille Henrot, 2013"),
        new CollectionArtwork("Time Smoking a Picture", "William Hogarth", "1761", "https://images.metmuseum.org/CRDImages/dp/original/DP825167.jpg", "Time Smoking a Picture, William Hogarth, 1761"),
        new CollectionArtwork("The Deep Sleep Sea", "Alice Maher", "", "https://imma.ie/wp-content/uploads/2019/03/6089.jpg", "The Deep Sleep Sea, Alice Maher"),
        new CollectionArtwork("Aquellos Polbos", "Francisco de Goya", "1797-98", "https://imma.ie/wp-content/uploads/2018/11/Francisco-de-Goya.-Aquellos-Polbos-That-Dust-1797-98.-Etching-and-aquatint.-21.7-x-14.8-cm.-Collection-Irish-Museum-of-Modern-Art.-Donation-Madden-Arnholz-Collection-1989..jpg", "Aquellos Polbos, Francisco de Goya, 1797-98"),
        new CollectionArtwork("Abstract", "Mary Swanzy", "", "https://imma.ie/wp-content/uploads/2022/08/124.jpg", "Abstract, Mary Swanzy"),
        new CollectionArtwork("Anthology", "Michael Craig-Martin", "2006", "http://www.artnet.com/WebServices/images/ll00341lldy7uGFgeQp42CfDrCWvaHBOc1GPD/michael-craig-martin-anthology.jpg", "Anthology, Michael Craig-Martin, 2006"),
        new CollectionArtwork("Night Time Go", "Karrabing Collective", "2017", "https://images.squarespace-cdn.com/content/v1/6030176a2990db0e610355f6/1614859503802-7Y17SUGPTQ5591V7OQWO/Screenshot+2021-02-25+at+16.13.32.png?format=1000w", "Night Time Go, Karrabing Collective, 2017"),
        new CollectionArtwork("INFINITY Minus Infinity", "The Otolith Group", "2019", "https://imma.ie/wp-content/uploads/2021/09/9489-1024x576.jpg", "INFINITY Minus Infinity, The Otolith Group, 2019"),
        new CollectionArtwork("Once Upon a time 1", "Patricia Hurl", "1986", "http://www.hurlrudin.com/images/Living_Room_Myths/Once_upon_a_time.jpg", "Once Upon a time 1, Patricia Hurl, 1986"),
        new CollectionArtwork("Blue Dyke", "Breda Lynch", "2021", "https://cdn.shopify.com/s/files/1/0167/9794/products/bluedyke22_large.jpg?v=1634559332", "Blue Dyke, Breda Lynch, 2021"),
        new CollectionArtwork("SWIRL", "Whorlasmz", "", "https://static.wixstatic.com/media/acf2c0_d27873edd4a7418e8c712144c446a221~mv2.jpeg/v1/fill/w_1196,h_1196,al_c,q_85,usm_0.66_1.00_0.01/acf2c0_d27873edd4a7418e8c712144c446a221~mv2.jpeg", "SWIRL, Whorlasmz"),

        new CollectionArtwork("Collar", "Alice Maher", "2003", "https://alicemaher.com/images/uploads/_medium/Collar.jpg", "Collar, Alice Maher, 2003"),
        new CollectionArtwork("Flock", "Alice Maher", "2003", "https://alicemaher.com/images/uploads/_medium/Flock.jpg", "Flock, Alice Maher, 2003"),
        new CollectionArtwork("Helmet", "Alice Maher", "2003", "https://alicemaher.com/images/uploads/_medium/Helmet.jpg", "Helmet, Alice Maher, 2003"),
        new CollectionArtwork("S'thombe, La Réunion", "Zanele Muholi", "2016", "https://imma.ie/wp-content/uploads/2021/03/2.-Zanele-Muholi.-Sthombe-La-Reunion-2016-I.-Quadriptych-Silver-Gelatin-Print.-David-Kronn-Collection-Promised-Gift-to-IMMA.-416x440.jpg", "S'thombe, La Réunion, Zanele Muholi, 2016"),
        new CollectionArtwork("Pride of Place", "Leanne McDonagh", "2016", "https://imma.ie/wp-content/uploads/2021/07/9471.jpg", "Pride of Place, Leanne McDonagh, 2016"),
        new CollectionArtwork("Blind Date", "Derek Jarman", "1992", "https://imma.ie/wp-content/uploads/2022/08/9486.jpg", "Blind Date, Derek Jarman, 1992"),
        new CollectionArtwork("Irish NAMES Project, AIDS Memorial Quilt", "Mary Shannon, including Family, lovers and/or friends of the deceased", "2003", "https://projectartscentre.ie/wp-content/uploads/2020/04/QUEER_web4-1-scaled.jpg", "Irish NAMES Project, AIDS Memorial Quilt, Mary Shannon, including Family, lovers and/or friends of the deceased, 2003"),
        new CollectionArtwork("CCTV Cameras, The Old Convent, Ballyhaunis", "Vukašin Nedeljkovic", "2008", "https://www.asylumarchive.com/uploads/1/3/7/3/13738784/1857525_1_orig.jpg", "CCTV Cameras, The Old Convent, Ballyhaunis, Vukašin Nedeljkovic, 2008"),
        new CollectionArtwork("Talking Ball", "Vukašin Nedeljkovic", "2011", "https://www.asylumarchive.com/uploads/1/3/7/3/13738784/2027483_1_orig.jpg", "Talking Ball, Vukašin Nedeljkovic, 2011"),
        new CollectionArtwork("Clock, found object in Gardiner House", "Vukašin Nedeljkovic", "2012", "https://www.asylumarchive.com/uploads/1/3/7/3/13738784/4955281_1_orig.jpg", "Clock, found object in Gardiner House, Vukašin Nedeljkovic, 2012"),
        new CollectionArtwork("Doll", "Vukašin Nedeljkovic", "2011", "https://www.asylumarchive.com/uploads/1/3/7/3/13738784/dsc-4150_2.jpg", "Doll, Vukašin Nedeljkovic, 2011"),
        new CollectionArtwork("Rocking Horse", "Vukašin Nedeljkovic", "2011", "https://www.asylumarchive.com/uploads/1/3/7/3/13738784/published/watergate-house-direct-provision-centre-dublin-1_2.jpg", "Rocking Horse, Vukašin Nedeljkovic, 2011"),
        new CollectionArtwork("The Past is a Foreign Country", "Anita Groener", "2018", "https://www.gibbonsnicholas.com/custom_images/2400x2400/usr/images/news/main_image/23/the-past-is-a-foreign-country-cropped-twenty-birch-trees-paper-twine-300-x-400-x-300-cm-with-nest-video-in-background-2-anita-groener-lcga-installation-shot-2018.jpg", "The Past is a Foreign Country, Anita Groener, 2018"),

        new CollectionArtwork("Two Heads", "Chinedum Muotto", "2021", "https://spiceimageworkaround.files.wordpress.com/2022/03/two-heads.jpg", "Two Heads, Chinedum Muotto, 2021"),

        new CollectionArtwork("Silver Stream", "Oberstown", "2022", "https://spiceimageworkaround.files.wordpress.com/2022/03/painting-1.jpg", "Silver Stream, Oberstown, 2022"),
        new CollectionArtwork("Painting 2", "Oberstown", "2022", "https://spiceimageworkaround.files.wordpress.com/2022/03/painting-2.jpg", "Painting 2, Oberstown, 2022"),
        new CollectionArtwork("The Potion of Knowledge", "Oberstown", "2022", "https://spiceimageworkaround.files.wordpress.com/2022/09/the-potion-of-knowledge2.jpg", "The Potion of Knowledge, Oberstown, 2022"),
        new CollectionArtwork("Painting 4", "Oberstown", "2022", "https://spiceimageworkaround.files.wordpress.com/2022/03/painting-4.jpg", "Painting 4, Oberstown, 2022"),
        new CollectionArtwork("Oberstown Uncovers", "Oberstown", "2022", "https://spiceimageworkaround.files.wordpress.com/2022/03/painting-5.jpg", "Oberstown Uncovers, Oberstown, 2022"),
        new CollectionArtwork("Desert Campaign", "Oberstown", "2022", "https://spiceimageworkaround.files.wordpress.com/2022/09/desert-campaign2.jpg", "Desert Campaign, Oberstown, 2022"),
        new CollectionArtwork("Shakey Bridge", "Oberstown", "2022", "https://spiceimageworkaround.files.wordpress.com/2022/09/shakey-bridge-final.jpg", "Shakey Bridge, Oberstown, 2022"),
        new CollectionArtwork("Untitled (horse and wagon)", "Oberstown", "2022", "https://spiceimageworkaround.files.wordpress.com/2022/09/untitled.jpg", "Untitled (horse and wagon), Oberstown, 2022"),
        new CollectionArtwork("Nice Set and Forget", "Oberstown", "2022", "https://spiceimageworkaround.files.wordpress.com/2022/09/nice-set-and-forget2.jpg", "Nice Set and Forget, Oberstown, 2022"),
        new CollectionArtwork("Damage  ☹☹", "Oberstown", "2022", "https://spiceimageworkaround.files.wordpress.com/2022/09/damage.jpeg", "Damage  ☹☹, Oberstown, 2022"),
        new CollectionArtwork("Diamond Bar", "Oberstown", "2022", "https://spiceimageworkaround.files.wordpress.com/2022/09/diamond-bar.png", "Diamond Bar, Oberstown, 2022"),
        new CollectionArtwork("Painting 12", "Oberstown", "2022", "https://spiceimageworkaround.files.wordpress.com/2022/03/painting-12.jpg", "Painting 12, Oberstown, 2022"),
        new CollectionArtwork("Don’t Look Back in Anger", "Oberstown", "2022", "https://spiceimageworkaround.files.wordpress.com/2022/09/dont-look-back-in-anger.jpg", "Don’t Look Back in Anger, Oberstown, 2022"),
        new CollectionArtwork("Shitting Bricks (1)", "Chinedum Muotto", "2021", "https://spiceimageworkaround.files.wordpress.com/2022/03/shitting-bricks.jpg", "Shitting Bricks (1), Chinedum Muotto, 2021"),
        new CollectionArtwork("Shitting Bricks (2)", "Chinedum Muotto", "2021", "https://spiceimageworkaround.files.wordpress.com/2022/03/240890012_223932422999776_6093921735585490178_n.jpg", "Shitting Bricks (2), Chinedum Muotto, 2021"),
        new CollectionArtwork("Shitting Bricks (3)", "Chinedum Muotto", "2021", "https://spiceimageworkaround.files.wordpress.com/2022/03/240997446_1268724926906821_3154896149459901426_n.jpg", "Shitting Bricks (3), Chinedum Muotto, 2021"),

        new CollectionArtwork("Yellow", "Amanda Coogan", "2008", "https://spiceimageworkaround.files.wordpress.com/2022/06/imm0821ng224-2500x1875-1.jpg", "Yellow, Amanda Coogan, 2008"),
        new CollectionArtwork("Open Season", "Women from the Family Resource Centre; Joe Lee", "1997", "https://spiceimageworkaround.files.wordpress.com/2022/06/open-season.png", "Open Season, Women from the Family Resource Centre; Joe Lee, 1997"),
        new CollectionArtwork("Railway Hostel Direct Provision Centre, Kiltimagh", "Vukašin Nedeljković", "2011-2012", "https://spiceimageworkaround.files.wordpress.com/2022/06/winner.png", "Railway Hostel Direct Provision Centre, Kiltimagh, Vukašin Nedeljković, 2011-2012"),
        new CollectionArtwork('Pray for More" campaign, Stuttgart, Germany', "Les Levine", "1988", "https://spiceimageworkaround.files.wordpress.com/2022/06/pray-for-more.png", 'Pray for More" campaign, Stuttgart, Germany, Les Levine, 1988'),
        new CollectionArtwork("Two Heads", "Chinedum Muotto", "2021", "https://spiceimageworkaround.files.wordpress.com/2022/06/img_3577.jpg", "Two Heads, Chinedum Muotto, 2021"),
        new CollectionArtwork("Two Heads", "Chinedum Muotto", "2021", "https://spiceimageworkaround.files.wordpress.com/2022/06/img_3574.jpg", "Two Heads, Chinedum Muotto, 2021"),
        new CollectionArtwork("Two Heads", "Chinedum Muotto", "2021", "https://spiceimageworkaround.files.wordpress.com/2022/06/img_3570.jpg", "Two Heads, Chinedum Muotto, 2021"),

        new CollectionArtwork("Tarantella", "Athanasius Kircher", "1641", "https://upload.wikimedia.org/wikipedia/commons/f/f3/Tarantella_%28Athanasius_Kircher%29.jpg", "Tarantella, Athanasius Kircher, 1641"),
        new CollectionArtwork("Broadway boogie-woogie", "Piet Mondrian", "1942", "https://media.timeout.com/images/102089467/image.jpg", "Broadway boogie-woogie, Piet Mondrian, 1942"),
        new CollectionArtwork("Music Note", "", "", "https://i.etsystatic.com/13386525/r/il/304c20/2417951462/il_fullxfull.2417951462_r3p8.jpg", "Music Note"),
        new CollectionArtwork("View of Vetheuil", "Claude Monet", "1880", "https://www.artofmasters.com/wp-content/uploads/2021/02/View-of-Vetheuil-1880-by-Claude-Monet-ORIGINAL-corrections24feb2021_1500px-776x1024.jpg", "View of Vetheuil, 1880, Claude Monet"),
        new CollectionArtwork("The Sound of Silence", "Max Ernst", "1943-44", "https://www.theartpostblog.com/wp-content/uploads/2017/06/the-sound-of-silence-max-ernst.jpg", "The Sound of Silence, Max Ernst, 1943-44"),

        new CollectionArtwork("Statement", "Tomasz Madajczak", "2022", "https://spiceimageworkaround.files.wordpress.com/2023/02/tomasz-statement-new.jpg", "Statement, Tomasz Madajczak, 2022"),
        new CollectionArtwork("Bengal Tiger Hunt", "Amna Walayat", "2020", "https://pbs.twimg.com/media/EfYLGazXkAAU_u-?format=jpg&name=4096x4096", "Bengal Tiger Hunt, Amna Walayat, 2020"),
        new CollectionArtwork("Evergreen", "Laragh Pittman", "2022", "https://spiceimageworkaround.files.wordpress.com/2023/02/evergreen.jpg", "Evergreen, Laragh Pittman, 2022"),
        new CollectionArtwork("Fear (ترس)", "Roxana Manouchehri", "2022", "https://spiceimageworkaround.files.wordpress.com/2023/02/fear.jpg", "Fear (ترس), Roxana Manouchehri, 2022"),
        new CollectionArtwork("Ravages of War", "Joe Odiboh", "2022", "https://spiceimageworkaround.files.wordpress.com/2023/02/ravages-of-war.jpg", "Ravages of War, Joe Odiboh, 2022"),
        new CollectionArtwork("The African Drum", "Antonio D’Souza", "2023", "https://spiceimageworkaround.files.wordpress.com/2023/02/the-african-drum.jpg", "The African Drum, Antonio D’Souza, 2023"),
        new CollectionArtwork("The African Drum (detail)", "Antonio D’Souza", "2023", "https://spiceimageworkaround.files.wordpress.com/2023/02/drum-detail-4.jpg", "The African Drum (detail), Antonio D’Souza, 2023"),
        new CollectionArtwork("BUPEI", "Ibrahim Mahama", "2017", "https://spiceimageworkaround.files.wordpress.com/2023/02/ibrahim-mahama-photo-a.dsouza.jpg", "BUPEI, Ibrahim Mahama, 2017"),

        new CollectionArtwork("Blighters", "Kevin Mooney", "2018-21", "https://imma.ie/wp-content/uploads/2022/09/Lead-Image-Blighters-e1668680677544.jpg", "Blighters, Kevin Mooney, 2018-21"),
        new CollectionArtwork("Carrier", "Kevin Mooney", "2021", "https://imma.ie/wp-content/uploads/2022/09/Carrier.jpg", "Carrier, Kevin Mooney, 2021"),
        new CollectionArtwork("Ilcruthach", "Kevin Mooney", "2021", "https://spiceimageworkaround.files.wordpress.com/2023/03/ilcruthach-162-x-130-cm-oil-and-distemper-on-jute-2021.jpg", "Ilcruthach, Kevin Mooney, 2021"),
        new CollectionArtwork("Mammal", "Kevin Mooney", "2020", "https://images.squarespace-cdn.com/content/v1/5c799b17755be23799b82d54/1604703117159-JCW839FINOFCCTR3ZN6N/Kevin+Mooney.jpg?format=500w", "Mammal, Kevin Mooney, 2020"),
        new CollectionArtwork("Puffs", "Kevin Mooney", "2018", "https://www.gibbonsnicholas.com/custom_images/2400x2400/usr/images/events/main_image/items/f7/f71f984a63f34acfaed3ac325abf1d5c/65-puffs-oil-on-canva-198-x-146cm-2018.jpg", "Puffs, Kevin Mooney, 2018"),
        new CollectionArtwork("Emigré", "Kevin Mooney", "2019", "https://imma.ie/wp-content/uploads/2022/09/Emigré.jpg", "Emigré, Kevin Mooney, 2019"),
        new CollectionArtwork("Orbs", "Kevin Mooney", "2018", "https://www.gibbonsnicholas.com/custom_images/2400x2400/usr/images/news/main_image/19/kevin-mooney80-x-60cm-orbs.jpg", "Orbs, Kevin Mooney, 2018"),
        new CollectionArtwork("Island", "Kevin Mooney", "2020", "https://spiceimageworkaround.files.wordpress.com/2023/03/island.jpg", "Island, Kevin Mooney, 2020"),
        new CollectionArtwork("Seer", "Kevin Mooney", "2021", "https://sample-studios.com/app/uploads/2021/12/Seer-55-x-45-cm-oil-and-distemper-on-jute-2021.jpg", "Seer, Kevin Mooney, 2021"),
        new CollectionArtwork("Bone Fire", "Kevin Mooney", "2021", "https://hillsborofineart.com/wp-content/uploads/2022/12/Mooney_Kevin_Bonefire.jpg", "Bone Fire, Kevin Mooney, 2021"),
        new CollectionArtwork("Peasant", "Kevin Mooney", "2018", "https://hillsborofineart.com/wp-content/uploads/2022/12/Mooney_Kevin_Peasant.jpg", "Peasant, Kevin Mooney, 2018"),
        new CollectionArtwork("Storyteller", "Kevin Mooney", "2016", "https://www.eva.ie/wp-content/uploads/2018/10/EVA-2018_Kevin-Mooney_Storyteller.jpg", "Storyteller, Kevin Mooney, 2016"),
        new CollectionArtwork("Mutator", "Kevin Mooney", "2021", "https://imma.ie/wp-content/uploads/2022/10/IMM1122KM108.jpg", "Mutator, Kevin Mooney, 2021"),
        new CollectionArtwork("B Movie", "Kevin Mooney", "2021", "https://hillsborofineart.com/wp-content/uploads/2022/06/Kevin-Mooney_BMovie-Hillsboro-Fine-Art.jpg", "B Movie, Kevin Mooney, 2021"),
        new CollectionArtwork("Seeing Cloud", "Kevin Mooney", "2016", "https://hillsborofineart.com/wp-content/uploads/2022/12/Mooney_Kevin_Seeing-Cloud.jpg", "Seeing Cloud, Kevin Mooney, 2016"),
        new CollectionArtwork("Beast", "Kevin Mooney", "2020", "https://www.westcorkartscentre.com/contentfiles/images/Exhibition%20Images/Arts%20Council/Kevin%20Mooney,%20Beast,%202020.jpg", "Beast, Kevin Mooney, 2020"),

        new CollectionArtwork("Madonna and Child (after Masaccio)", "Patricia Hurl", "1984-85", "https://imma.ie/wp-content/uploads/2022/12/ph1-scaled.jpg", "Madonna and Child (after Masaccio), Patricia Hurl, 1984-85"),
        new CollectionArtwork("The Kerry Babies Trial", "Patricia Hurl", "1985", "https://imma.ie/wp-content/uploads/2022/12/ph2-scaled.jpg", "The Kerry Babies Trial, Patricia Hurl, 1985"),
        new CollectionArtwork("Jingle Bells", "Patricia Hurl", "1986-87", "https://imma.ie/wp-content/uploads/2022/12/ph4.jpg", "Jingle Bells, Patricia Hurl, 1986-87"),
        new CollectionArtwork("Irish Gothic (Living Room)", "Patricia Hurl", "", "https://imma.ie/wp-content/uploads/2023/01/Patricia-Hurl_Irish-Gothic-1.jpg", "Irish Gothic (Living Room), Patricia Hurl"),
        new CollectionArtwork("Adam and Eve (after Masaccio)", "Patricia Hurl", "", "http://www.hurlrudin.com/images/Living_Room_Myths/Adam_Eve_after_Masaccio.jpg", "Adam and Eve (after Masaccio), Patricia Hurl"),
        new CollectionArtwork("Once Upon a Time", "Patricia Hurl", "1986", "http://www.hurlrudin.com/images/Living_Room_Myths/Once_upon_a_time_2.jpg", "Once Upon a Time, Patricia Hurl, 1986"),
        new CollectionArtwork("Hush a Bye Baby", "Patricia Hurl", "1986", "http://www.hurlrudin.com/images/Living_Room_Myths/Hush_a_bye_baby.jpg", "Hush a Bye Baby, Patricia Hurl, 1986"),
        new CollectionArtwork("The Company Wife", "Patricia Hurl", "", "https://spiceimageworkaround.files.wordpress.com/2023/03/hurl4.png", "The Company Wife, Patricia Hurl"),
        new CollectionArtwork("Warrior X", "Patricia Hurl", "", "https://spiceimageworkaround.files.wordpress.com/2023/03/hurl3.png", "Warrior X, Patricia Hurl"),
        new CollectionArtwork("Warrior II", "Patricia Hurl", "", "https://spiceimageworkaround.files.wordpress.com/2023/03/warrior.png", "Warrior II, Patricia Hurl"),
        new CollectionArtwork("And she never even read Turgenev", "Patricia Hurl", "", "https://spiceimageworkaround.files.wordpress.com/2023/03/hurl5.png", "And she never even read Turgenev, Patricia Hurl"),
        new CollectionArtwork("Living Room", "Patricia Hurl", "", "https://spiceimageworkaround.files.wordpress.com/2023/03/hurl2.png", "Living Room, Patricia Hurl")

    ]

}